DROP TABLE IF EXISTS COLORS;

CREATE TABLE COLORS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  red INTEGER NOT NULL,
  green INTEGER NOT NULL,
  blue INTEGER DEFAULT NULL,
  timestamp BIGINT DEFAULT NOT NULL
);